apiVersion: v1
kind: Secret
metadata:
  name: homeobs-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/RajeenKalee/homeobs.git
