apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/RajeenKalee/homeobs.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
